Стилизация главной страницы
htmlacademy-adaptive/929085-cat-energy-21 pull request #5
Opened 2020-11-20 13:44 UTC by kate-mors

2020-11-22 06:43 UTC, Manyaka requested changes

2020-11-22 06:43 UTC, Manyaka commented on source/less/global/variables.less
> +@mobile-width-only: 320px;
```suggestion
@mobile-width: 320px;
```

2020-11-22 06:43 UTC, Manyaka commented on source/less/global/variables.less
> +@font-oswald: "Oswald", "Arial", sans-serif;
Тут не хватает умолчательных шрифтов для Мака и Линукса

2020-11-22 06:43 UTC, Manyaka commented on source/less/blocks/button.less
> +.button--active {
Моды можно писать через родительский селектор, попробуй, пока есть возможность, поймешь - удобно ли тебе так писать или нет

2020-11-22 06:43 UTC, Manyaka commented on source/less/blocks/contacts.less
> +  background-image: url("../../img/Map.png");
все картинки должны называться маленькими буквами

2020-11-22 06:43 UTC, Manyaka commented on source/less/blocks/page.less
> +  font-family: "Arial", sans-serif;
Не хватает умолчательных шрифтов для Мака и Линукса

2020-11-22 06:43 UTC, Manyaka commented on source/less/blocks/page-main.less
> +  font-family: "Oswald", "Arial", sans-serif;
Ты сделала для этого переменную

2020-11-22 06:43 UTC, Manyaka commented on source/less/blocks/page.less
> +  font-weight: 400;
Проверь какой вес у шрифта

2020-11-22 06:44 UTC, Manyaka commented
![Uploading Screenshot 2020-11-22 at 09.42.27.png…]()

2020-11-22 06:45 UTC, Manyaka commented
![Screenshot 2020-11-22 at 09 42 27](https://user-images.githubusercontent.com/6417966/99897063-66282680-2ca7-11eb-8ecc-4aadee7f9e0d.png)

2020-11-22 06:45 UTC, Manyaka commented
![Screenshot 2020-11-22 at 09 39 34](https://user-images.githubusercontent.com/6417966/99897070-70e2bb80-2ca7-11eb-8ed7-a95bc40c22e7.png)

2020-11-22 06:45 UTC, Manyaka commented
![Screenshot 2020-11-22 at 09 36 45](https://user-images.githubusercontent.com/6417966/99897072-79d38d00-2ca7-11eb-98a5-deddf795f3c6.png)

2020-11-22 06:46 UTC, Manyaka commented
![Screenshot 2020-11-22 at 09 13 32](https://user-images.githubusercontent.com/6417966/99897078-835cf500-2ca7-11eb-9244-23792e5090cd.png)

2020-11-22 14:54 UTC, kate-mors commented on source/less/style.less
> +@import "global/fonts.less";
Copy that

2020-11-22 15:32 UTC, kate-mors commented on source/less/global/variables.less
> +@mobile-width-only: 320px;
Done

2020-11-22 15:33 UTC, kate-mors commented on source/less/global/variables.less
> +@font-oswald: "Oswald", "Arial", sans-serif;
Done

2020-11-22 15:33 UTC, kate-mors commented on source/less/blocks/button.less
> +.button--active {
Need to discuss

2020-11-22 15:33 UTC, kate-mors commented on source/less/blocks/contacts.less
> +  background-image: url("../../img/Map.png");
Copy

2020-11-22 15:33 UTC, kate-mors commented on source/less/blocks/page.less
> +  font-family: "Arial", sans-serif;
Done

2020-11-23 05:22 UTC, Manyaka commented on source/less/blocks/page.less
> +  font-family: "Arial", sans-serif;
Можешь, пож, не писать всякие сделано и приняла, только ответы и вопросы по существу. А для данов я предлагаю использовать эмодзи - глазки, тк другими эмодзями я пользуюсь. Мне отбивки приходят на почту.

2020-11-23 05:23 UTC, Manyaka commented on source/less/blocks/button.less
> +.button--active {
Если тебе нужно обсудить, сразу пиши сюда в коменты, что нужно обсудить, это функционал гитхаба как раз для этого и создан :)

2020-11-23 10:02 UTC, Manyaka commented on source/less/global/variables.less
> +@font-oswald: "Oswald", "Arial", sans-serif;
Расположи их в правильном порядке

2020-11-23 10:03 UTC, Manyaka commented on source/less/blocks/contacts.less
> +  background-image: url("../../img/Map.png");
Переименую ещё саму картинку

2020-11-23 10:04 UTC, Manyaka commented on source/less/blocks/page.less
> +  font-family: "Arial", sans-serif;
Расположи их в правильном порядке

2020-11-23 12:05 UTC, kate-mors commented on source/less/blocks/page.less
> +  font-weight: 400;
![Screen Shot 2020-11-23 at 13 04 31](https://user-images.githubusercontent.com/70647825/99960133-8d0c5880-2d8c-11eb-998d-128ed0ca4c9e.png)

2020-11-23 12:26 UTC, Manyaka commented on source/less/blocks/page.less
> +  font-weight: 400;
Я пока резолвить коммент не буду, чтобы запомнить.

2020-11-24 06:21 UTC, Manyaka commented on source/less/blocks/page.less
> +  font-weight: 400;
В обновленной системе вес 400

2020-11-24 09:10 UTC, Manyaka requested changes

2020-11-24 09:10 UTC, Manyaka commented on source/less/blocks/button.less
> +    background-color: #5eaa2f;
Тебе надо писать код единообразно. Если ты используешь переменные для цветов, то тебе надо их использовать везде.

2020-11-24 09:10 UTC, Manyaka commented on source/less/blocks/button.less
> +    background-color: #5eaa2f;
Поправь везде.

2020-11-24 09:10 UTC, Manyaka commented on source/less/blocks/contacts.less
> +.contacts--contrast-background {
```suggestion
.contacts {
  &--contrast-background {
```

2020-11-24 09:10 UTC, Manyaka commented on source/less/blocks/contacts.less
> +.contacts--contrast-background {
И ещё удобнее это перенести в начало файла, тк `.contacts` - это их корневой блок по бэму

2020-11-24 09:10 UTC, Manyaka commented on source/less/blocks/contacts.less
> +  background: @basic-grey;
Если это только цвет, то нужно использовать `background-color`, потому что общее свойство бг - составное, поэтому оно обнуляет все другие значения. Это может использоваться только сознательно, но не для того, чтобы задать цвет бекграунда

2020-11-25 06:32 UTC, merged